generator:
  class: sfDoctrineGenerator
  param:
    model_class:           phPhoto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ph_photo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at:
          label: Crée le
        filename:
          label: Fichier
      list:
        title: Liste des photos
        display: [id, _filename, created_at]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
