generator:
  class: sfDoctrineGenerator
  param:
    model_class:            acTag
    theme:                  admin
    non_verbose_templates:  true
    with_show:              false
    singular:               ~
    plural:                 ~
    route_prefix:           ac_tag
    with_doctrine_route:    true
    actions_base_class:     sfActions

    config:
      actions:              ~
      fields:               ~
      list:
        title:              Liste des tags
        display:            [nom]
      filter:
        display:            [nom]
      edit:
        title:              Editer un tag
      new:
        title:              Ajouter un tag
