generator:
  class: sfDoctrineGenerator
  param:
    model_class:           elPoste
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          el_poste
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:    ~
      fields:     ~
      list:
        title:    Liste des postes
        display:  [=nom, _description]
      filter:     ~
      form:       ~
      edit:
        title:    Editer '%%nom%%'
      new:
        title:    Ajouter un poste
