generator:
  class: sfDoctrineGenerator
  param:
    model_class:           wmWeekmail
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~

    plural:                ~
    route_prefix:          wm_weekmail
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:  Liste des weekmails
        display: [=objet]
        object_actions:
          render:
            label: Afficher
          send:
            label: Envoyer
            params:
              confirm: "Are you sure?"
          _edit: ~
          _delete: ~
      filter:
        display: [objet]
      form: ~
      edit:
        title: Editer '%%objet%%'
      new:
        title: Ajouter un weekmail
