generator:
  class: sfDoctrineGenerator
  param:
    model_class:           gaPhoto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ga_photo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        filename:
          label: Fichier
      list:
        title: Liste des photos des grandes activités
        display: [_activite_id, _filename]
      filter:
        display: [activite_id]
      form:
        display: [activite_id, filename]
      edit:
        title: Editer une photo
      new:
        title: Ajouter une photo
