generator:
  class: sfDoctrineGenerator
  param:
    model_class:           suBugTracker
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          su_bug_tracker
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        deadline:
          label: Délai
        problem:
          label: Problème
        created_at:
          label: Crée le
      list:
        title: Liste des demandes informatique
        display: [ _created_at, _deadline, statut, _problem]
      filter:
        display: [deadline, statut, problem, created_at]
      form:    ~
      edit:
        title: Modifier une demande informatique
      new:
        title: Ajouter une demande informatique
